### ISSUE TITLE
无法登录！提示“验证码错误”

### ISSUE THREAD

**Issue by fordxdd** [openkaios/bilibili_kaios#5]
Nokia 6300 4G无法登录。永远提示“验证码错误”。也没见哪儿可以填验证码啊！

**Comment by zixing131** [comment]
不好意思，目前是这样的，需要验证码的机器是无法登录的，开发者们目前还没解决这个问题，所以只能先凑合用了。

**Comment by fordxdd** [comment]
> 不好意思，目前是这样的，需要验证码的机器是无法登录的，开发者们目前还没解决这个问题，所以只能先凑合用了。

ah shit!!!!可以快点适配吗？或者有没有其他解决方法？

**Comment by zixing131** [comment]
该问题已经通过扫码登录间接解决
